### ISSUE TITLE
Oscillation around 0 elevation for spacecrafts

### ISSUE THREAD

**Issue by ghost** [brandon-rhodes/pyephem#87] opened 2015-10-06 07:35 UTC
For our needs at ground station we usually track satellites from -5 degrees elevation till -5 degrees. And during the operations we observed one strange thing - from -5 till 0 and from 0 till -5 calculations are oscillating. 2 spreadsheets with plots (Github don't want to attach them):

[Links deleted]

Note: time periods indicated in the filenames are for predictions from 0 till 0 degrees of elevation. Time resolution is 3 seconds.

**Comment by dmopalmer** [comment] 2015-10-18 02:43
DO NOT CLICK ON THE LINKS

THIS SITE TRIED TO INFECT MY MAC

**Comment by digitalvapor** [comment] 2015-10-18 02:57
gentoo will fix that
On Oct 17, 2015 7:43 PM, "David Palmer" <notifications@github.com> wrote:

DO NOT CLICK ON THE LINKS

THIS SITE TRIED TO INFECT MY MAC

—
Reply to this email directly or view it on GitHub
<https://github.com/brandon-rhodes/pyephem/issues/87#issuecomment-148971368>
.

**Comment by cnts-ab** [comment] 2015-10-24 08:54
Strange... This situation could be avoided if GitHub supported truly open formats like .ods, and not only .xlsx. I tried to upload .xlsx but GitHub reported failure :\ Some comments regarding the issue itself? I don't want to switch my project to pypredict, it will take time :(

**Comment by dmopalmer** [comment] 2015-10-24 14:35
A snippet of python that replicates the problem is better than a just a spreadsheet showing the result.
Give the specific TLE, observer location, time, etc.

Are you using a set of ra,dec that includes atmospheric refraction?  That could cause a problem.  (If you are pointing a radio antenna, you should probably set your observer to have zero atmospheric pressure)

**Comment by cnts-ab** [comment] 2015-10-24 14:45
Now I call that a hint :-) Yeah, we are using radio antennas. Didn't know about temp and pressure for Observer. Will test on Monday, when I will get to the system

**Comment by cnts-ab** [comment] 2015-10-27 14:37
I've set pressure to zero - it didn't help, the same problem persists. Any ideas?

**Comment by dmopalmer** [comment] 2015-10-28 04:42
Try creating a minimal python program that demonstrates the behavior so that it can be debugged.

**Comment by cnts-ab** [comment] 2015-10-28 13:17
Code: http://pastebin.com/DyYTvFca
It needs this: http://pastebin.com/8bdks5yA
As you can see I tried pressure and horizon (together and separately) - both doesn't help, problem persists

**Comment by dmopalmer** [comment] 2015-10-29 02:20
The solution to your problem is 1), below.  2) is just something to watch out for.

I haven't run your code, since it appears to use the system clock to track the satellite in realtime, so I couldn't debug except at the actual time of the pass.

However, a couple of things:

1) You have code
``` 
    degrees_alt, minutes_alt, seconds_alt = str(sat_alt).split(':')
    altitude = str(float(degrees_alt) + (float(minutes_alt) * 1/60) + (float(seconds_alt) * 1/60 * 1/60))
```
which illustrates one of the major gotchas of sexagesimal formatting.  When your code sees an altitude of `-2:06:36`, it calculates 
`(-2) + (6/60) + (36/3600)= -1.89`
  whereas it should calculate 
`-1 * ((2) + (6/60) + (36/3600)) = -2.11`
You can see why that would cause sawtooth patterns below the horizon.

Instead, you want to use the floating point value of sat_alt (which will be in radians) and convert to degrees:
```
altitude = float(sat_alt)/ephem.degree
```

2) You have `print sat_alt` instead of `print(sat_alt)` which implies that you are using python2.  However, you also have `1/60` in various places, which under python2 would evaluate to 0 if you are not careful.  It doesn't show up in your case because you have `float(blah) * 1/60` which fortunately calculates the `*1` (giving a float) before the `/60`, but it is something to watch out for.  When I use python2.7 I always stick 
```from __future__ import division,print_function```
at the top so that integer division doesn't attack me (unless I intentionally use the `//` integer division operator) and so that I don't have to worry about python 2 vs 3.

**Comment by cnts-ab** [comment] 2015-10-29 09:53
Thank you so much! Perfect answer! I was blind... Problem solved!

**Comment by brandon-rhodes** [comment] 2021-01-08 21:29
I am not sure why I didn't close this issue after a satisfactory answer was given; did I have some tweak or fix in mind as a result of the conversation? If so then I've forgotten it. Thanks for jumping in and being helpful here, @dmopalmer, I'll close this issue now!

**Closed by brandon-rhodes** 2021-01-08 21:29 UTC
