### ISSUE TITLE
test_date_constructor fails on powerpc and hppa

### ISSUE THREAD

**Issue by olebole** [brandon-rhodes/pyephem#100] opened 2016-02-06 08:52 UTC
The `test_date_constructor` test fails on [PowerPC/32](https://buildd.debian.org/status/fetch.php?pkg=pyephem&arch=powerpc&ver=3.7.6.0-1&stamp=1454679502) and [PA-RISC](https://buildd.debian.org/status/fetch.php?pkg=pyephem&arch=hppa&ver=3.7.6.0-1&stamp=1454685021):

```
FAIL: test_date_constructor (ephem.tests.test_dates.DateTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ephem/tests/test_dates.py", line 48, in test_date_constructor
    construct_and_compare(arg1, arg2)
  File "ephem/tests/test_dates.py", line 22, in construct_and_compare
    % (d1.tuple(), args1, d2.tuple(), args2))
AssertionError: dates not equal:
 (2004, 9, 4, 0, 17, 15.799999977461994) = date'2004/09/04 00:17:15.8'
 (2004, 9, 4, 0, 17, 15.635205055586994) = date'2004/9/4.0119884259259257'
```

Both architectures are big endian; there are however other big endian archs, that succeed, for example  [PowerPC/64](https://buildd.debian.org/status/fetch.php?pkg=pyephem&arch=ppc64&ver=3.7.6.0-1&stamp=1454685697).

**Comment by brandon-rhodes** [comment] 2016-02-08 03:40
Drat! Is there a third-party integration tool that I could use to reproduce this issue so that I can work on it myself? I don't have access to those processors on any of my own machines.

Also, I need to know which C compiler was used when compiling PyEphem on those systems — it could be, for example, that its `double` is only 32 bits instead of 64, which would produce the inaccuracy and truncation that seem to be happening here.

Hopefully we can get this fixed!

**Comment by olebole** [comment] 2016-02-08 08:27
In principle, we could ask for a guest account for you; however this is a [bit formalized](https://dsa.debian.org/doc/guest-account/). If you would do this, please send me the information as written there, I will sponsor them. It may be however faster if you would have a test program what I could run or what I should out on the machines (I myself can access those machines directly). The C compiler on powerpc is gcc-5.3.1 (same version as on the other platforms), I just tested that the length of `double` is 64 bit, and the accuracy is 54 bits (as usual).

**Comment by albertw** [comment] 2016-02-10 22:35
Since CPU architectures were mentioned I took a look on SPARC. This case also fails there:

**Comment by albertw** [comment] 2016-02-10 23:29
Ole's patch resolves this on sparcv9 but only when using gcc. Solaris Studio doesn't have __BYTE_ORDER__ etc. defined.

The proposed fix doesn't make things any worse on sparcv9 than it already is, but being compiler specific isn't ideal.

I need to ask around and see what's the suggested way to address this in Studio.

**Comment by olebole** [comment] 2016-02-11 07:47
I'd recommend to use the [`PyOS_string_to_double()`](https://docs.python.org/2.7/c-api/conversion.html?highlight=strtod#c.PyOS_string_to_double) function: since pyephem needs Python anyway, I can't see a drawback here. I just didn't have the time to get this running.

**Comment by brandon-rhodes** [comment] 2021-11-26 22:56
Apologies if this is still an outstanding problem, but as I can see that I merged your fix for this in August 2016, I'm going to tentatively go ahead and close this issue. If that's in error, simply re-open and I'll be happy to discuss further!

**Closed by brandon-rhodes** 2021-11-26 22:56 UTC
