### ISSUE TITLE
Potential incorrect geodetic to geocentric latitude conversion

### ISSUE THREAD

**Issue by bsmigs** [brandon-rhodes/pyephem#136] opened 2018-03-27 20:37 UTC
Hi there, I was going through the `earthsat.c` file in `pyephem/libastro-3.7.7/earthsat.c` and in the method `GetSitPosition(...),` Line 637, I noticed you had:

`Lat = atan(1/(1-SQR(EarthFlat))*tan(SiteLat));`

I checked MATLAB (their function `geocentricLatitude `-- which takes the geodetic latitude and flattening factor as inputs) as well as David Vallado's book _Fundamentals of Astrodynamics and Applications_ and found those resources are consistent on how to calculate the geocentric latitude from the geodetic latitude when you are on the surface of the ellipsoid. Following their lead, I believe the correct expression is:

`Lat = atan(SQR(1-EarthFlat)*tan(SiteLat));`

In Vallado's book, the expression is on pg. 148 and provides it in terms of eccentricity, but it's a simple matter to convert that to be a function of the flattening factor.

**Comment by drbitboy** [comment] 2018-04-09 14:38
This is a bug in libastro, not pyephem _per se_, right?  So this will need to be pushed upstream to xephem?

Anyway, I can confirm that bsmigs' analysis is correct in this Issue ...

**Quick sanity check**

The formula in [earthsat.c, line 637](https://github.com/brandon-rhodes/pyephem/blob/master/libastro-3.7.7/earthsat.c#L637) is equivalent to:

    tan(Lat) = (1/(1-SQR(Earthflat))) * tan(SiteLat),

Which means, for **0 < EarthFlat < 1** i.e. an oblate spheroid, the magnitude of the tangent of a calculated topocentric (geocentric) latitude (Lat, above) will be greater than that of its  corresponding non-zero **_geodetic_** latitude (SiteLat, above).

Since d**tan(theta)**/d**theta** is always > 0, the magnitude of a calculated geocentric latitude output will be always **calculated as greater** than that of its corresponding non-zero geodetic latitude input.

But for an oblate spheroid, a surface point normal (geodetic) vector will point pole-ward relative to the surface point (geocentric) vector; "pole-ward" is farther from the equator, and the equator represents the zero for latitude, so **qualitatively** we can say that the magnitude of any geocentric latitude **must be less** than that of its corresponding non-zero geodetic latitude.

Therefore the current [formula](https://github.com/brandon-rhodes/pyephem/blob/master/libastro-3.7.7/earthsat.c#L637) in earthsat.c **must be incorrect**.  Whether or not bmsigs (above) and I (below) did our math right, I am fairly certain this statement must stand.

N.B. the derivation by bmsigs of the Vallado formula passes this sanity check:

    SQR(1-EarthFlat) < 1
and so

    ||Lat|| < ||SiteLat||

**Geometric derivation**

I also did the geometry from scratch, and I am pretty sure the Vallado formula quoted by bsmigs is correct.

**Part I:  semi-axes and flattening formula**

    a = semi-major axis
    b = semi-major axis
    EarthFlat = (a-b) / a
a = earth equatorial radius, 3,963.2 mi, cf. [here](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00010.tpc); search for BODY399_RADII
b = earth polar radius, 3,949.9 mi

Solve for b:

    b = a (1-EarthFlat)

**Part II:  two-dimensional ellipse formula relating topocentric and geodetic latitudes of a surface point**

Two-dimensional ellipse formula for a surface point [x,y] at **_topocentric_** latitude **_SiteLat_**:

         2        2
    (x/a)  + (y/b)   = 1
where x is the distance of the surface point from the polar axis,
and y is the distance of the surface point above the equatorial plane,
and **tan(Lat) = y/x**, where Lat is the topocentric (geocentric) latitude at [x,y], and for which we are trying to solve.

Replace exponents of 2 in ellipse formula with SQR macro from earthsat.c:

    SQR(x/a) + SQR(y/b) = 1

Substitute **a(1-EarthFlat)** for **b** from the flattening formula derivation above (**Part I**), and multiply through by SQR(a):

    SQR(x)  + SQR(y/(1-EarthFlat))  = SQR(a)
Take differentials, then solve for dy/dx, which yields the slope of the North-South-going surface tangent at [x,y]

    2x dx + 2y/SQR(1-EarthFlat) dy = 0

    dy/dx = -SQR(1-EarthFlat)   x/y
[Sanity check:  in the first quadrant (x>0 and y>0), surfaces' slopes should negative, and they are.]

The slope of the **_normal_** to surface at [x,y], which is also the tangent of the **_geodetic_** latitude, **tan(Lat)**, will be **-dx/dy**:

    -dx/dy = tan(SiteLat) = 1/SQR(1-EarthFlat)   y/x
[Sanity check:  in the first and fourth quadrants, the normals' slopes should be positive and negative, respectively, and they are; also for a circle (EarthFlat=0), all normals' slopes should be equal to y/x, and they are.]

And since **y/x** is by definition tan(Lat), the tangent of the topocentric (or geocentric) latitude, we get

    tan(SiteLat) = 1/SQR(1-EarthFlat)   tan(Lat)
Rearrange:

    tan(Lat) = SQR(1-EarthFlat)  tan(SiteLat)
and

    Lat = atan( SQR(1-EarthFlat)   tan(SiteLat) ),
which is bsmigs' derivation of the Vallado formula.

QED

**Comment by brandon-rhodes** [comment] 2018-04-11 12:06
Thanks very much, @bsmigs, not only for the report, but for doing the work to figure out the correct solution and to write up working code! And thanks, @drbitboy, for the follow-up analysis that saves me so much time as project maintainer!

I think we should keep this issue open and plan to patch PyEphem — and I'll happily accept a pull request, @bsmigs, if you're interested in writing one up. I think we should patch PyEphem's copy of libastro when we find actual bugs, because XEphem is no longer maintained, so there's no way to upstream our improvements — the maintainer said in a 31 Oct 2016 email:

“Some of you quickly noticed I recently removed XEphem from my web site. I didn't think there was much interest any longer  so I was surprised at the outpouring of everything from anger to grief. … [So] I have resurrected most of the XEphem web site, including a page for downloading all the source code and data sets. There is no longer a commercial edition, I offer no support and I do not expect to make any future updates”

So, upon reflection, I think that maintaining 1:1 agreement with libastro's bugs or inaccurate calculations in XEphem no longer makes sense. Going forward, most of my attention will be on Skyfield, but when outright bugs like this exist in PyEphem or libastro, let's go ahead and land a fix!

**Comment by drbitboy** [comment] 2018-04-11 12:19
Good plan.

An alternative to consider longer term would be to put XEphem as a standalone repo on Github, with proper attribution to Mr. Downey, to *try* to ensure there is One True Source going forward (i.e. to get any fixes from other users e.g. the Lisp wrapper), and possibly to benefit from others' fixes.  Since your focus is on SkyField, I don't think this is worth it, but just wanted to mention it.

**Comment by drbitboy** [comment] 2018-04-11 13:12
here ya' go:  https://github.com/brandon-rhodes/pyephem/pull/137

**Comment by drbitboy** [comment] 2018-04-11 13:26
> the XEphem maintainer insisted in the 31 Oct 2016 email that XEphem would not become open source

Hmm, then we should not change the code itself, but implement fixes as patch files that are automatically run as part of the build.  Makes it easier in case the maintainer does something upstream.  A bit of a Rube Goldberg, but emphasizes the original author.

Or we just make a clean break, say there is no formal upstream other than attributions, and never look back.

Either way works, don't you think?

**Comment by brandon-rhodes** [comment] 2018-04-12 13:37
Oh — I was responding to why I don't think it's possible for you to put XEphem in a GitHub repository. I don't have any problems with us landing edits to PyEphem's internal copy of libastro, and in fact many edits had to be made right at the beginning to get PyEphem working well, so it's always been a fork of the open source libastro library. (Does that explain / clear things up? I haven't had coffee yet.)

**Comment by oldwonder** [comment] 2018-04-20 15:02
Hi, are there anyway you can verify this fix? When I tried this fix, the site position I got seems to be way off.

**Comment by brandon-rhodes** [comment] 2018-04-20 15:04
@oldwonder Interesting! Could you provide a tiny script together with the output before and after, so we have a concrete example to investigate? Thanks!

**Comment by oldwonder** [comment] 2018-04-20 15:40
`import ephem
from skyfield.api import load
from skyfield.iokit import parse_celestrak_tle
from skyfield.toposlib import Topos
import math

observer = ephem.Observer()
observer.lat = '42.362153'
observer.lon = '-71.102982'
observer.elevation = 18
observer.date = '2018/2/27 00:00:00'

line1 = 'XM-3 (RHYTHM)'
line2 = '1 28626U 05008A   18056.63101463 -.00000224  00000-0  00000+0 0  9999'
line3 = '2 28626   0.0156 309.6837 0000327 323.4990  24.2823  1.00269747 47644'
xm3 = ephem.readtle(line1, line2, line3)
xm3.compute(observer)
pyEphemDistance = xm3.range

satellite = dict(parse_celestrak_tle([line1, line2, line3]))[line1]
difference = satellite - Topos('42.362153 N', '71.102982 W', None, None, 18)
topocentric = difference.at(load.timescale().utc(2018, 2, 27, 00, 00, 00))
alt, az, distance = topocentric.altaz()
skyfieldDistance = distance.m

print 'Discrepancy: ' + str(math.fabs(pyEphemDistance - skyfieldDistance))
# Using PyEphem with the coordinate conversion fix outputs 15292.458716
# Using PyEphem without the fix outputs 191.541283958`

**Comment by brandon-rhodes** [comment] 2018-04-20 15:41
Let's first see what @drbitboy gets when he tries your script both with and without his fix!

**Comment by oldwonder** [comment] 2018-04-20 15:42
Great! Thanks Brandon.

**Comment by brandon-rhodes** [comment] 2018-04-20 16:11
@oldwonder Oh, and: note that you can put three back-ticks on a line by themselves at the top, and at the bottom, of a file if you want to include it in your comment — like this:
```
This is a small
file.
```

**Comment by drbitboy** [comment] 2018-04-20 21:29
are those results (15300.458716 and 183.541283958) in m or km or summat else?

**Comment by drbitboy** [comment] 2018-04-21 13:35
**Update**

I changed the latitude in oldwonder's script to be zero, and the discrpency between PyEphem and Skyfied is constant (102m) between the old and new versions of PyEphem.  This re-confirms the obvious, that the 15km change has to be in the flattening calculation.

I am starting to think that Mr. Downey took a different, but correct, approach to flattening than I assumed, and that the formula 1/(1-SQR(EarthFlat)) is correct for that approach.  Could this entire issue has been a wild goose chase?  That would be funny.

**Comment by drbitboy** [comment] 2018-06-30 09:54
> Should I revert the merged pull request here in PyEphem?

Probably.

**Details**

I don't have time to do any more research right now, but my gut feel is that, after checking with bsmigs (the OP), you should revert the change until we can prove it one way or the other.

**Comment by brandon-rhodes** [comment] 2018-06-30 14:18
I'm going to close this for now, but feel free to re-open in the future if a failing test can be written up — that an improvement would fix — showing a clearly wrong result for latitude. In the meantime, I'll keep this closed. Thanks for all the investigation!

**Closed by brandon-rhodes** 2018-06-30 14:18 UTC
